name: laptop_habour
description: "A new Flutter project."


publish_to: 'none'










# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html


version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'







dependencies:
  flutter:
    sdk: flutter




  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.5.1
  shared_preferences: ^2.2.2
  google_fonts: ^6.2.1
  dio: ^5.4.2+1
  cached_network_image: ^3.3.1
  firebase_core: ^2.22.0
  firebase_auth: ^4.13.0
  intl: ^0.19.0
  iconly: ^1.0.1
  firebase_storage: ^11.7.0
  cloud_firestore: ^4.16.0
  flutter_screenutil: ^5.9.0
  fluttertoast: ^8.2.4
  font_awesome_flutter: ^10.7.0
  flutter_local_notifications: ^17.0.1
  permission_handler: ^11.3.1
  flutter_rating_bar: ^4.0.1
  modal_bottom_sheet: ^3.0.0
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter






  flutter_lints: ^3.0.0





flutter:




  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/laptops/


