// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRAjgilU2h6tasnn__xUBYfDxt6CBH9f0',
    appId: '1:1082589581165:android:f99b347ab470f572cb1464',
    messagingSenderId: '1082589581165',
    projectId: 'com-example-laptop-habour',
    databaseURL: 'https://com-example-laptop-habour-default-rtdb.firebaseio.com',
    storageBucket: 'com-example-laptop-habour.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqdVqf3JIz_LmH-msjuYA_hRVjV04qxx8',
    appId: '1:1082589581165:ios:bfb352e7e810f443cb1464',
    messagingSenderId: '1082589581165',
    projectId: 'com-example-laptop-habour',
    databaseURL: 'https://com-example-laptop-habour-default-rtdb.firebaseio.com',
    storageBucket: 'com-example-laptop-habour.appspot.com',
    iosBundleId: 'com.example.laptopHabour',
  );
}
